/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTabs: typeof import('./components/AppTabs.vue')['default']
    CredentialsSection: typeof import('./components/pageSections/CredentialsSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IntroductionSection: typeof import('./components/pageSections/IntroductionSection.vue')['default']
    ProjectsSection: typeof import('./components/pageSections/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
